services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      REDIS_ADDR: "redis:6379"
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: "redis"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
